language: java
sudo: false
jdk:
- openjdk15
services:
- docker
before_script:
- pwd
- ls
script:
- "./gradlew pushImage"
env:
  global:
  - secure: EAfspGDhJqDrtZ3I7bSt1DzFMvqXv8DchSapr3hSkf4mLas62QsupHWkFZzf15MZQS811mmKXFv4R/ww/GjnMZgYxqtxd67cskk1GYeK95K1QCZe2/jPVf0kV2gYsmDuoslf+VFphNpOyJtA52Fb2hvR8jMOwCXUD05KZ3qEB1NPTh/LGagQIur3h+/1LPBE3bSVz904XigtvnXXmCVRBDyiCgVPk771B7N4S3J6mZKZDUhsXYwOOTUWYEyW0ZdLMqCGHqMGSbVxi9zrl/0Z3DbJzosOnKp+guUST9uMd/R607pjZmii+P1eBPE7vud80QHBPYUBEJe8KfaeL3kEnwcfcFSya7SFINTZ2zpNjIEUtlp16gwB/rj0g7E+lcE3B7oHNqMB+7SJL8mVt8/gtAWIpr7dH5aY8ZxARqqU2ERtn91M86Ob2WFBDn9a4/ogI3fXhYieqJO9oFh9oChKw2GVZ3Ru/IME37mUU+MNFcSVWAaYXcPYwkrChotKeTSLh6OUriyR2rv5G8GkXK4ky9snYdhnsTf6S4U86NkrCop0JbKMXlI0y0oLIJPoUxx777RmkQZpVmqnGJm21aLW93aBo+BbLq6ZZT4txv0sR2xSoByVnS98FwaylKlTfien2BAvwA883UN0iEUVhKFIHOTFZTSy5pm8brCVpThjVLI=
  - secure: OnOEGqp2S/fimnYcqEMmil5yi1p9YAD5FRlX/5eNVxvVILHc7bBZidsZwbUwiHzO5wpCTP664c6m2qu4tGSKwKlYTF2Vcdh+zDenf/avBP+HzIEW7EW3xptec9KF8Xcfjg3al6BTc5fCRBCj3ve7IcXcq98YHh2WWlQ2d5xf7i70UzUblB94tlSxg/xbtaBKJwU3bwoiz8EF1F66ft1Nbz2lXCjuAqxmaRLL/805xCb7X7Y5kmkULRryRIi5l/sw7DEzvfTemPbOgjd+F6spREjgQJhD+RFkEh3HV0nUiqhj1UebfM2gpdYMYaFbga1urVg3hqgaItw/Xk8bA62reELizc2eyPG6P6XWJbtjFpXIb6iG9sEeF3FgXYPeBqpx3Jh1vDslO9VbjX+G/GqLZvBjHfAfxTNWa6U90noP6MlC9sTgIu5vZKPzFshdtlCFgjjLBF24AJvQBfpfVF3QVBZABgEu1WUr/kzaZh6QkwX7mDHQkpKgD9TZPQ6VzHRg22U6eStZshc4eoV4CXKHmTN1JtNMoTFyncW6JaKr4NoiIkmLdZXGnkzOJftaKpL/lr6hAj8JtOs9BzhUHQMzy88KeA/wehDef4TiYHb53vwajfsyJOa34hWVWud35TLVFn8m/AKTqUuq/sVBqYVhzQcTAj3iXXjDuMXvLd8uLU4=
