language: java
install: skip

jdk:
  - openjdk15

services:
  - docker


script:
  - env
  - ./gradlew pushImage

env:
  global:
  - secure: UiKer1ap3oV4yXmV0wnqcGQAZXcfJeCSmrPXYcwzRiPD7aqeVz+OGXvqDeynCeShaNSUn5kNCn89xGrncVgUPMIPgCVAdcBXv5NnbIiwzESHBL/QefG939cGIEGSE7IP9CGnEO/0GAoVf/0cDlPpNexQ60htDUgIHQ0pFCiv/XPFhqMTWciMsV4NmCDsyr1eZ3aduAKRjzR1Iydv0vmq2Y6GlbA4x1iReemfppsOyQsGIyiJQzqzBxbVz3dTI9PSI3i2LIBz2SZqLDZMI5/YSmvSPYwQcqB9ohqa0HkISqnDodKFILmnMXN8sCvrUpu5ATbR1GfYIqqBvTQVKGvKKzzRZpiSY/2yXaHM1OJnAyamprq0j6NFtIW820XgTy02A0COupKly83C/rres7Ph6fg7zFNCQ+L4n+w6nG9i1mqQy4xioTDO1FxA7Tcvhep4XaYyKJ97j5akUjmdUgzk3F0+cMMToKMR/m+3kktTwLDlH7pkMy3eXgNrmlzhFWTGXu7GM3AX1UmuB7Z8kcZ9MHy/DkpibmYTj/mNT2ZD39WGDBysdOysXcVYiwOAsfNiQF+1vMpEtKA5TUWXDnLjFXU6XdXWnPZvqjz4zB/X4ozL64nqDBXul1p++ki7+HHmTNIKm4BxT9YHAZvY0CRvDpYKtPPGo6XU34BFijbUgg4=
  - secure: dFkpzJkzBUEijTCV9NoAbDcB8EXYTVSAmlsGCkm5oFMM682hAuqIRTesijdF3reXoRYr1ibfI87pwGV/Oy0ImI0MW2+EmDsED0BWoLEf+C+//784GXs5ne2oswcXo/3bm0aTUJeQalsgg8Uza8k2UbBSx0eTbdVnxX1/nCMWnbsWhu1fnfchVcr/09KXboXB3x0Td3V9vlJbSBE5ATSChkdPtBfKQkrw5DmPkPRrI69hKowsugmFiwZMJpUMoTYFzLKCfdUrnm4GfCi3hZrDR6ih1N96QQF5KqjcI9OTAmFix9snQhYfQasWCaTuk/6jKTkbsWhUSqlplHic3ekmnQqTPx7C8pikEPpJpskajocCflRzfoCfqr8NA8mPRVvyOefPmygkKt4ETSw3+he8iDVlKSV5e343cvZgMAIx+rPQLWw97dAc+pVsVbrLSluJWMvTIla0fzCU24FEPpyypWJCrPMOvXXv9d1hKPB83pWonflCzEXAJLmsQ1MiCrB91EthbczF2ofigUugNhiOR9SbR/5T2n6hCzOCfwVsqw1FpgSd5qEPUbsDjcIr5drQUqlJZgX1x+5X0jV4SlrymTu6mTSOFeC/nKjmucsBjVj0aQYSg2kgnWEcIYpztIhPJEc1PN7dSZ358E4FhSHiZxYTVGc4XWRddaoNb8+SpA4=
  - secure: afStjghlXZnnS7pAbvI0R2RVjXSXGFsjj0D4X1WQLzYeBz+ky/NdRK/C4jyD6TRnSR7hIQGkGxzwARO+qN1h+JpEFbpqwHNYDA5F9Wydy9SgT+/JxcPPZn4r7b0UX3YttJi5scjlmPR2X6FEsE9GxZwElgMXd54FyHXfKhbr0LPsiy0U5p47IA/8gtapPs9lAjoBwfYWa6Hk+85eLR2Nuta08QDNTlYSnJbmi4oiCwesSUKiWVhSWYh4oDxJsmeDNfA+j1cepLcE7UIC3Y6t5TNfdNWhUQ0/LhUkvDtgyQvXLhsPCaSgH45yiH5t6lHUuaC5RhU+BnUYK3FIqjoWuc+MGVkF/QY/1pkto7NfLXGl9cSOLmNyewmCbjpau1H5zeP1zVtnBAKX/V5NH+N4/SgocZIJHzhPo6OiWmOxpR9/SWMt3nO0/cuVGplvfOuVZxLr9TOqKcUklWXQQ95B0rmHNIGBMCIElvS/HyEQUdo0Z8EUMZEMiRXwPwX9Qm5Q7xvDA2e59oK2zSRtr6XCROr3fc4Lp7Ni6S6XLx82qm8DZ7S0HCm1GGk/nF9BieiQT5AM+3hoRlCWzAQcntJKxyO9FbWES/O5aYTXqmMet4qTfOGXOjZD0fUBL8fL0mvNqNb3IS6YnfakplZqG7SMR4kdsrMdhTWoYEp/n3XZH3Q=
